#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 25/09/2026 14:48
# Generated By: david
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$txtResult = New-Object System.Windows.Forms.TextBox
$BtnCreer = New-Object System.Windows.Forms.Button
$lblFichier = New-Object System.Windows.Forms.Label
$txtFichier = New-Object System.Windows.Forms.TextBox
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$handler_BtnCreer_Click= 
{
	# $txtResult.Text += 'Hello world !'
	if ($txtFichier.Text.Trim() -eq '') {
		$txtResult.Text = "La saisie du champ Fichier est obligatoire"
		$txtFichier.Focus()
	}
	else {
		try {
			$res = New-Item $txtFichier.Text 
			$txtResult.Text = $res | Out-String
		} catch {
			$txtResult.Text = $_ | Out-String
		}
	}
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 196
$System_Drawing_Size.Width = 199
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Primal Form"

$txtResult.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 1
$System_Drawing_Point.Y = 79
$txtResult.Location = $System_Drawing_Point
$txtResult.Multiline = $True
$txtResult.Name = "txtResult"
$txtResult.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 112
$System_Drawing_Size.Width = 194
$txtResult.Size = $System_Drawing_Size
$txtResult.TabIndex = 3

$form1.Controls.Add($txtResult)


$BtnCreer.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 35
$System_Drawing_Point.Y = 32
$BtnCreer.Location = $System_Drawing_Point
$BtnCreer.Name = "BtnCreer"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 39
$System_Drawing_Size.Width = 125
$BtnCreer.Size = $System_Drawing_Size
$BtnCreer.TabIndex = 2
$BtnCreer.Text = "Créer"
$BtnCreer.UseVisualStyleBackColor = $True
$BtnCreer.add_Click($handler_BtnCreer_Click)

$form1.Controls.Add($BtnCreer)

$lblFichier.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$lblFichier.Location = $System_Drawing_Point
$lblFichier.Name = "lblFichier"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 17
$System_Drawing_Size.Width = 59
$lblFichier.Size = $System_Drawing_Size
$lblFichier.TabIndex = 1
$lblFichier.Text = "Fichier :"

$form1.Controls.Add($lblFichier)

$txtFichier.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 77
$System_Drawing_Point.Y = 6
$txtFichier.Location = $System_Drawing_Point
$txtFichier.Name = "txtFichier"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txtFichier.Size = $System_Drawing_Size
$txtFichier.TabIndex = 0

$form1.Controls.Add($txtFichier)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
