# Créer un formulaire avec 4 champs texte : nom, prénom, service et mot de  passe
# et un bouton OK avec l'évènement Click
# un champ texte multi-ligne  et lecture seule pour afficher le résultat


# Créer le compte dans l'AD dans votre OU
# en ayant pris soin de valider la saisie de tous les champs texte
# vérifier que le mot de passe  fait plus de 7 caractères et contient des min ,maj et chiffres

#Requires -PSEdition Desktop
#Requires -Modules ActiveDirectory

#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 25/09/2026 15:45
# Generated By: david
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$txtResult = New-Object System.Windows.Forms.TextBox
$lblPassword = New-Object System.Windows.Forms.Label
$lblService = New-Object System.Windows.Forms.Label
$lblNom = New-Object System.Windows.Forms.Label
$lblPrenom = New-Object System.Windows.Forms.Label
$btnCreer = New-Object System.Windows.Forms.Button
$txtPassword = New-Object System.Windows.Forms.TextBox
$txtService = New-Object System.Windows.Forms.TextBox
$txtNom = New-Object System.Windows.Forms.TextBox
$txtPrenom = New-Object System.Windows.Forms.TextBox
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$btnCreer_OnClick=
{
    if ($txtPrenom.Text.Trim() -eq '') {
        $txtResult.Text = "Le champ Prénom est obligatoire"
        $txtPrenom.Focus()
    } elseif ($txtNom.Text.Trim() -eq '') {
        $txtResult.Text = "Le champ Nom est obligatoire"
        $txtNom.Focus()
    } elseif ($txtService.Text.Trim() -eq '') {
        $txtResult.Text = "Le champ Service est obligatoire"
        $txtService.Focus()
    } elseif ($txtPassword.Text.Length -lt 7 -or $txtPassword.Text -cnotmatch '[a-z]' -or $txtPassword.Text -cnotmatch '[A-Z]' -or $txtPassword.Text -notmatch '[0-9]') {
        $txtResult.Text = "Le champ mot de passe n'est pas valide 7 caractères minimum avec au moins 1 min, 1 maj et 1 chiffre"
        $txtPassword.Focus()
    } else {
        try {
            $params = @{
                Name = $txtPrenom.Text + ' ' + $txtNom.Text
                SamAccountName = $txtPrenom.Text + '.' + $txtNom.Text
                UserPrincipalName = $txtPrenom.Text + '.' + $txtNom.Text + '@dawan.local'
                AccountPassword = ConvertTo-SecureString $txtPassword.Text -Force -AsPlainText
                Department = $txtService.Text
                Enabled = $true
                ChangePasswordAtLogon = $true
                Path = 'ou=david,dc=dawan,dc=local'
            }
            New-ADUser @params
            $txtResult.Text = "Utilisateur créé $($params.SamAccountName)"
        }
        catch {
            $txtResult.Text = "Erreur à la création du compte `r`n $($_ | Out-String)"
        }
    }
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 261
$System_Drawing_Size.Width = 284
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Primal Form"

$txtResult.Anchor = 15
$txtResult.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 1
$System_Drawing_Point.Y = 148
$txtResult.Location = $System_Drawing_Point
$txtResult.Multiline = $True
$txtResult.Name = "txtResult"
$txtResult.ReadOnly = $True
$txtResult.ScrollBars = 3
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 109
$System_Drawing_Size.Width = 278
$txtResult.Size = $System_Drawing_Size
$txtResult.TabIndex = 9
$txtResult.WordWrap = $False

$form1.Controls.Add($txtResult)

$lblPassword.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 18
$System_Drawing_Point.Y = 95
$lblPassword.Location = $System_Drawing_Point
$lblPassword.Name = "lblPassword"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 16
$System_Drawing_Size.Width = 83
$lblPassword.Size = $System_Drawing_Size
$lblPassword.TabIndex = 8
$lblPassword.Text = "Mot de passe :"

$form1.Controls.Add($lblPassword)

$lblService.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 18
$System_Drawing_Point.Y = 69
$lblService.Location = $System_Drawing_Point
$lblService.Name = "lblService"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 15
$System_Drawing_Size.Width = 83
$lblService.Size = $System_Drawing_Size
$lblService.TabIndex = 7
$lblService.Text = "Service :"

$form1.Controls.Add($lblService)

$lblNom.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 18
$System_Drawing_Point.Y = 40
$lblNom.Location = $System_Drawing_Point
$lblNom.Name = "lblNom"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 16
$System_Drawing_Size.Width = 83
$lblNom.Size = $System_Drawing_Size
$lblNom.TabIndex = 6
$lblNom.Text = "Nom :"

$form1.Controls.Add($lblNom)

$lblPrenom.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 18
$System_Drawing_Point.Y = 16
$lblPrenom.Location = $System_Drawing_Point
$lblPrenom.Name = "lblPrenom"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 15
$System_Drawing_Size.Width = 83
$lblPrenom.Size = $System_Drawing_Size
$lblPrenom.TabIndex = 5
$lblPrenom.Text = "Prénom :"

$form1.Controls.Add($lblPrenom)


$btnCreer.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 85
$System_Drawing_Point.Y = 119
$btnCreer.Location = $System_Drawing_Point
$btnCreer.Name = "btnCreer"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 93
$btnCreer.Size = $System_Drawing_Size
$btnCreer.TabIndex = 4
$btnCreer.Text = "Créer"
$btnCreer.UseVisualStyleBackColor = $True
$btnCreer.add_Click($btnCreer_OnClick)

$form1.Controls.Add($btnCreer)

$txtPassword.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 112
$System_Drawing_Point.Y = 93
$txtPassword.Location = $System_Drawing_Point
$txtPassword.Name = "txtPassword"
$txtPassword.PasswordChar = '*'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txtPassword.Size = $System_Drawing_Size
$txtPassword.TabIndex = 3

$form1.Controls.Add($txtPassword)

$txtService.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 112
$System_Drawing_Point.Y = 66
$txtService.Location = $System_Drawing_Point
$txtService.Name = "txtService"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txtService.Size = $System_Drawing_Size
$txtService.TabIndex = 2

$form1.Controls.Add($txtService)

$txtNom.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 112
$System_Drawing_Point.Y = 39
$txtNom.Location = $System_Drawing_Point
$txtNom.Name = "txtNom"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txtNom.Size = $System_Drawing_Size
$txtNom.TabIndex = 1

$form1.Controls.Add($txtNom)

$txtPrenom.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 112
$System_Drawing_Point.Y = 12
$txtPrenom.Location = $System_Drawing_Point
$txtPrenom.Name = "txtPrenom"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txtPrenom.Size = $System_Drawing_Size
$txtPrenom.TabIndex = 0

$form1.Controls.Add($txtPrenom)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm







